const railway = {
    stations: {
        A_main: { x: -325, y: 125, name: 'A站', city: 'A' },
        A_minor: { x: -224, y: 27, name: 'A东站', city: 'A' },
        B: { x: 560, y: -685, name: 'B站', city: 'B' },
        C: { x: -235, y: -237, name: 'C站', city: 'C' },
        D: { x: 682, y: -1434, name: 'D站', city: 'D' },
        E: { x: -110, y: -950, name: 'E站', city: 'E' },
        F: { x: 16, y: -1194, name: 'F站', city: 'F' },
        G: { x: 222, y: -855, name: 'G站', city: 'G' },
        H: { x: 343, y: 102, name: 'H站', city: 'H' }
    },
    midpoints: {
        midpoint_A1: { x: -313, y: 233 },
        midpoint_A11: { x: -314, y: 227 },
        midpoint_A2: { x: -295, y: 245 },
        midpoint_A12: { x: -300, y: 244 },
        midpoint_A0: { x: -231, y: 242 },
        midpoint_A3: { x: -213, y: 228 },
        midpoint_A4: { x: 11, y: 246 },
        midpoint_A5: { x: 176, y: 91 },
        midpoint_C1: { x: -207, y: -481 },
        midpoint_C2: { x: -192, y: -558 },
        midpoint_C3: { x: -192, y: -918 },
        midpoint_C4: { x: -145, y: -940 },
        midpoint_E1: { x: -42, y: -948 },
        midpoint_E2: { x: -29, y: -955 },
        midpoint_E3: { x: -30, y: -1155 },
        midpoint_E4: { x: -14, y: -1175 },
        midpoint_E5: { x: 93, y: -937 },
        midpoint_E6: { x: 184, y: -860 },
        midpoint_B1: { x: 540, y: -864 },
        midpoint_B2: { x: 563, y: -835 },
        midpoint_B3: { x: 553, y: -826 },
        midpoint_B4: { x: 653, y: -932 },
        midpoint_B5: { x: 677, y: -1222 },
        midpoint_D1: { x: 639, y: -1171 },
        midpoint_D2: { x: 688, y: -1222 }
    },
    lines: [
        ['station_A_main', 'midpoint_A1'],
        ['station_A_main', 'midpoint_A11'],
        ['midpoint_A1', 'midpoint_A2'],
        ['midpoint_A11', 'midpoint_A12'],
        ['midpoint_A12', 'midpoint_A0'],
        ['midpoint_A0', 'midpoint_A3'],
        ['midpoint_A3', 'station_A_minor'],
        ['station_A_minor', 'station_C'],
        ['midpoint_A2', 'midpoint_A4'],
        ['midpoint_A4', 'midpoint_A5'],
        ['midpoint_A5', 'station_H'],
        ['station_C', 'midpoint_C1'],
        ['midpoint_C1', 'midpoint_C2'],
        ['midpoint_C2', 'midpoint_C3'],
        ['midpoint_C3', 'midpoint_C4'],
        ['midpoint_C4', 'station_E'],
        ['station_E', 'midpoint_E1'],
        ['midpoint_E1', 'midpoint_E2'],
        ['midpoint_E2', 'midpoint_E3'],
        ['midpoint_E3', 'midpoint_E4'],
        ['midpoint_E4', 'station_F'],
        ['station_E', 'midpoint_E5'],
        ['midpoint_E5', 'midpoint_E6'],
        ['midpoint_E6', 'station_G'],
        ['station_G', 'midpoint_B1'],
        ['midpoint_B1', 'midpoint_B2'],
        ['midpoint_B2', 'station_B'],
        ['station_B', 'midpoint_B3'],
        ['midpoint_B3', 'midpoint_B4'],
        ['midpoint_B4', 'midpoint_B5'],
        ['midpoint_B5', 'station_D'],
        ['station_F', 'midpoint_D1'],
        ['midpoint_D1', 'midpoint_D2'],
        ['midpoint_D2', 'station_D']
    ]
};
